name: vconda
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=he0c23c2_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=h32ff316_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - ffmpeg=8.0.0=gpl_he3062b8_906
  - filelock=3.20.0=pyhd8ed1ab_0
  - fmt=12.0.0=h29169d4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313hd650c13_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - giflib=5.2.2=h7edc060_0
  - glib=2.86.2=h19e2e61_1
  - glib-tools=2.86.2=he647baa_1
  - glslang=16.1.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - harfbuzz=12.2.0=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_1
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudnn-dev=9.10.2.21=hca898b4_0
  - libcudss=0.7.1.4=hca898b4_0
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_15
  - libglib=2.86.2=h0c9aed9_1
  - libgomp=15.2.0=h8ee18e1_15
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmagma=2.9.0=hb6a17ea_3
  - libmagma_sparse=2.9.0=h6290ce1_3
  - libmpdec=4.0.0=h2466b09_0
  - libnpp=12.4.1.87=hac47afa_1
  - libnvjitlink=12.9.86=hac47afa_2
  - libnvjpeg=12.4.0.76=hac47afa_1
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_2
  - librsvg=2.60.0=hd5e4115_0
  - libsqlite=3.51.1=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libtorch=2.9.1=cuda128_mkl_hbf96477_300
  - libusb=1.0.29=h1839187_0
  - libuv=1.51.0=hfd05255_1
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.7=h4fa8253_0
  - markupsafe=3.0.3=py313hd650c13_0
  - matplotlib=3.10.6=py313haa95532_1
  - matplotlib-base=3.10.6=py313he1ded55_1
  - mkl=2025.3.0=hac47afa_454
  - mlxtend=0.23.4=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - numpy=2.3.5=py313hce7ae62_0
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - optree=0.18.0=py313hf069bd2_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - pango=1.56.4=h03d888a_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.0.0=py313h38f99e1_2
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py313h1048830_2
  - pyqt5-sip=12.17.0=py313hfe59770_2
  - python=3.13.11=h09917c8_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytorch=2.9.1=cuda128_mkl_py313_h7f80487_300
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=hb098fff_6
  - scikit-learn=1.7.2=py313he28f1d7_0
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.28=h5112557_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=haa9a63f_0
  - sip=6.10.0=py313hfe59770_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - spirv-tools=2025.4=h49e36cd_0
  - statsmodels=0.14.6=py313h0591002_0
  - svt-av1=3.1.2=hac47afa_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - torchcodec=0.8.1=cuda128_py313_h436bcac_3
  - torchvision=0.24.1=cuda129_py313_hf5c7d43_0
  - tornado=6.5.2=py313h5ea7bf4_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zlib-ng=2.3.2=h5112557_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - audiomentations==0.43.1
      - audioop-lts==0.2.2
      - audioread==3.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - idna==3.11
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.1
      - msgpack==1.1.2
      - numba==0.62.1
      - numpy-minmax==0.5.0
      - numpy-rms==0.6.0
      - pooch==1.8.2
      - pycparser==2.23
      - python-stretch==0.3.1
      - requests==2.32.5
      - scipy==1.16.3
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - standard-aifc==3.13.0
      - standard-chunk==3.13.0
      - standard-sunau==3.13.0
      - torchaudio==2.9.1
      - tqdm==4.67.1
      - urllib3==2.6.0
prefix: C:\Users\Admin\miniconda3\envs\vconda
